#!/bin/bash -e

here=$(dirname $(readlink -f $0))
cd $here

if [ $# -eq 0 ] ; then
	echo "Launching unit tests in docker"
	exec ./dev-shell ./unit-test indocker
fi

set -x

build=$(mktemp -d -p $here)
cd $build

../cmake-init.sh
ninja aktualizr-lite t_lite-helpers t_compose-bundles libt_lite-mock.so uptane-generator make_ostree_sysroot

clang_tests=$(ninja help | grep aktualizr_clang_tidy-src- | cut -d: -f1)
ninja $clang_tests

clang_tests=$(ninja help | grep aktualizr_ci_clang_format-src- | cut -d: -f1)
ninja $clang_tests

ctest -V -R test_lite-helpers
ctest -V -R test_compose-bundles
ctest -V -R test_aktualizr-lite
